CREATE TABLE matches (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL REFERENCES users(id),
    opponent_name VARCHAR(255) NOT NULL,
    match_date    DATE         NOT NULL,
    notes         TEXT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE match_sets (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id       BIGINT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    set_number     INT    NOT NULL,
    player_score   INT    NOT NULL,
    opponent_score INT    NOT NULL,
    CONSTRAINT uq_match_sets_match_set UNIQUE (match_id, set_number)
);

CREATE INDEX idx_matches_user_date ON matches (user_id, match_date DESC);
CREATE INDEX idx_matches_user_opponent ON matches (user_id, lower(opponent_name));
